name: Generate Snake Animation

on:
  # æ¯å¤© UTC æ—¶é—´ 0 ç‚¹è¿è¡Œä¸€æ¬¡
  schedule:
    - cron: "0 0 * * *"
  
  # å…è®¸æ‰‹åŠ¨è§¦å‘å·¥ä½œæµ
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          # ğŸ‘‡ è¿™é‡Œæ”¹æˆä½ çš„ GitHub ç”¨æˆ·å
          github_user_name: Jamin-cn
          
          # ç”Ÿæˆçš„æ–‡ä»¶è¾“å‡ºåˆ° dist ç›®å½•
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # å°†ç”Ÿæˆçš„æ–‡ä»¶å‘å¸ƒåˆ° gh-pages åˆ†æ”¯
          publish_branch: gh-pages
